[2023-06-30T05:34:34.507+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: order-letter_NER.read_order_from_mail manual__2023-06-30T05:33:07.927789+00:00 [queued]>
[2023-06-30T05:34:34.552+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: order-letter_NER.read_order_from_mail manual__2023-06-30T05:33:07.927789+00:00 [queued]>
[2023-06-30T05:34:34.553+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 6
[2023-06-30T05:34:35.011+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): read_order_from_mail> on 2023-06-30 05:33:07.927789+00:00
[2023-06-30T05:34:35.077+0000] {standard_task_runner.py:57} INFO - Started process 1885 to run task
[2023-06-30T05:34:35.144+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'order-letter_NER', 'read_order_from_mail', 'manual__2023-06-30T05:33:07.927789+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/order-letter-extraction.py', '--cfg-path', '/tmp/tmp153g8l1j']
[2023-06-30T05:34:35.148+0000] {standard_task_runner.py:85} INFO - Job 53: Subtask read_order_from_mail
[2023-06-30T05:34:35.434+0000] {task_command.py:410} INFO - Running <TaskInstance: order-letter_NER.read_order_from_mail manual__2023-06-30T05:33:07.927789+00:00 [running]> on host f7b244b51c6e
[2023-06-30T05:34:36.690+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Abin Jilson' AIRFLOW_CTX_DAG_ID='order-letter_NER' AIRFLOW_CTX_TASK_ID='read_order_from_mail' AIRFLOW_CTX_EXECUTION_DATE='2023-06-30T05:33:07.927789+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-30T05:33:07.927789+00:00'
[2023-06-30T05:38:24.040+0000] {local_task_job_runner.py:291} WARNING - State of this instance has been externally set to queued. Terminating instance.
[2023-06-30T05:38:24.088+0000] {process_utils.py:131} INFO - Sending Signals.SIGTERM to group 1885. PIDs of all processes in the group: [1885]
[2023-06-30T05:38:24.099+0000] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 1885
[2023-06-30T05:38:24.103+0000] {taskinstance.py:1517} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-06-30T05:38:24.140+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/order-letter-extraction.py", line 67, in read_order_from_mail
    time.sleep(10)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1519, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-06-30T05:38:24.160+0000] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=order-letter_NER, task_id=read_order_from_mail, execution_date=20230630T053307, start_date=20230630T053434, end_date=20230630T053824
[2023-06-30T05:38:24.284+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 53 for task read_order_from_mail (Task received SIGTERM signal; 1885)
[2023-06-30T05:38:24.401+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=1885, status='terminated', exitcode=1, started='05:34:34') (1885) terminated with exit code 1
