[2023-06-29T07:48:42.765+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: order-letter_NER.extract_product_and_quantity scheduled__2023-06-27T00:00:00+00:00 [queued]>
[2023-06-29T07:48:42.782+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: order-letter_NER.extract_product_and_quantity scheduled__2023-06-27T00:00:00+00:00 [queued]>
[2023-06-29T07:48:42.783+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 6
[2023-06-29T07:48:42.809+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): extract_product_and_quantity> on 2023-06-27 00:00:00+00:00
[2023-06-29T07:48:42.817+0000] {standard_task_runner.py:57} INFO - Started process 2422 to run task
[2023-06-29T07:48:42.826+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'order-letter_NER', 'extract_product_and_quantity', 'scheduled__2023-06-27T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/order-letter-extraction.py', '--cfg-path', '/tmp/tmpb1n6g0k4']
[2023-06-29T07:48:42.830+0000] {standard_task_runner.py:85} INFO - Job 11: Subtask extract_product_and_quantity
[2023-06-29T07:48:42.924+0000] {task_command.py:410} INFO - Running <TaskInstance: order-letter_NER.extract_product_and_quantity scheduled__2023-06-27T00:00:00+00:00 [running]> on host 0eb747d9e0f2
[2023-06-29T07:48:43.052+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Abin Jilson' AIRFLOW_CTX_DAG_ID='order-letter_NER' AIRFLOW_CTX_TASK_ID='extract_product_and_quantity' AIRFLOW_CTX_EXECUTION_DATE='2023-06-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-27T00:00:00+00:00'
[2023-06-29T07:48:43.054+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: extract_product_and_quantity() missing 1 required positional argument: 'content'
[2023-06-29T07:48:43.067+0000] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=order-letter_NER, task_id=extract_product_and_quantity, execution_date=20230627T000000, start_date=20230629T074842, end_date=20230629T074843
[2023-06-29T07:48:43.092+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 11 for task extract_product_and_quantity (extract_product_and_quantity() missing 1 required positional argument: 'content'; 2422)
[2023-06-29T07:48:43.125+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-29T07:48:43.150+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
